### PR TITLE
Allow non-fn arguments

### PR DESCRIPTION
**Pull request by ajoslin**
This is the last thing I need to replace my fancy es6 utility function I use everywhere:

```js
const callAll = (...fns) => arg => fns.map(fn => fn && fn(arg))
```

### CODE REVIEW

**Comment by bendrucker** [comment]
Hmm I don't think I like the idea of having functions be optional. Plus they should be filtered out at construction time instead of on call.

**Comment by ajoslin** [comment]
My main usecase is this sort of thing, where any could be optional: https://github.com/ajoslin/react-stepper-primitive/blob/master/src/index.js#L109

My other use case in the past has been removing event listeners. eg `unlisten = callAll(listen1() listen2(), listen3())`

I could do `onBlur: callAll([props.onBlur, this.handleBlur].filter(Boolean))`, but that would suck. 

Are you sure you don't want to add this?

**Comment by bendrucker** [comment]
I think it makes more sense to do `[].filter(Boolean)`. IMO optional args isn't expected for a library like this.

**Comment by ajoslin** [comment]
OK

**Pull request closed without merging**
